TURISMOREAL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.views import SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # urls del include
    path('', include('arriendo.urls')),

    #para django all_auth
    #path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

arriendo/urls.py
from django.urls import path
from .views import CancelReservaView, DeptoListView, DeptoDetailView,\
                    ReservaListView, ubicaciones, registro

app_name='arriendo'

urlpatterns = [
    path('home/', DeptoListView,name='DeptoListView'),#antes url llamada "depto_list"
    path('reserva_list/', ReservaListView.as_view(),name='ReservaListView'),#"as_view" pq en views.py esta declaraddo como clase y no como funcion
    path('depto/<category>',DeptoDetailView.as_view(), name='DeptoDetailView'),
    path('ubicaciones/', ubicaciones,name='Ubicaciones'),
    path('registro/', registro, name='registro'),
    # <pk> es lo qe usan los generic views
    path('reserva/cancel/<pk>',CancelReservaView.as_view(), name='CancelReservaView'),
]

arriendo/models.py
from django.db import models
from django.conf import settings
from django.db.models.fields import IntegerField

#para redireccion a eliminar una reserva 
from django.urls import reverse_lazy

# Create your models here.
class Depto(models.Model):
    
    DEPTO_CATEGORIES = (
        #1er parametro = key value
        #2do parametro = value neto
        ('VIN','Vina del Mar'),
        ('SER','La Serena'),
        ('PUC','Pucon'),
        ('VIL','Villarrica'),
        ('VAL','Valdivia'),
        ('IQU','Iquique'),
        ('FRU','Frutillar'),
    )
    category = models.CharField(max_length=3, choices=DEPTO_CATEGORIES,default='Iquique')
    precio = models.IntegerField()
    capacidad = models.IntegerField()
    camas = models.IntegerField()

    def __str__(self):
        return self.category

class Reserva(models.Model):
    #id del cliente 
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    depto = models.ForeignKey(Depto, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'{self.user} ha reservado depto en {self.depto}, desde {self.check_in} hasta {self.check_out}'
    
    # fx que posteriormente servirá para qe un usuario pueda ver su lista de reservas con el nombre de categoria(ciudad)
    # completo en vez del acronimo. (osea 'Pucon' en vez de 'PUC')
    def get_depto_category(self):
        depto_categories = dict(self.depto.DEPTO_CATEGORIES)
        depto_category = depto_categories.get(self.depto.category)
        return depto_category
    
    def get_cancel_reserva_url(self):
        return reverse_lazy('arriendo:CancelReservaView',args=[self.pk,])

arriendo/forms.py
#from typing_extensions import Required
from django import forms
from django.forms.fields import ChoiceField
from django.contrib.auth.forms import UserCreationForm
#from django.views.generic.list import T

class AvailabilityForm(forms.Form):
    check_in =  forms.DateTimeField(required=True, input_formats=["%Y -%m -%dT%H:%M",]) #'%m/%d/%Y'
    check_out = forms.DateTimeField(required=True, input_formats=["%Y -%m -%dT%H:%M",]) # "%Y -%m -%dT%H:%M"

class CustomCreationForm(UserCreationForm):
    pass

arriendo/views.py
from django import http
from django.shortcuts import redirect, render, HttpResponse
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import DeleteView
from .models import Depto, Reserva
from .forms import AvailabilityForm, CustomCreationForm
from arriendo.reserva_functions.availability import check_availability
from arriendo.reserva_functions.get_depto_cat_url_list import get_depto_cat_url_list
from arriendo.reserva_functions.get_depto_category_human_format import get_depto_category_human_format
from arriendo.reserva_functions.get_available_deptos import get_available_deptos
from arriendo.reserva_functions.book_depto import book_depto
from django.contrib.auth import authenticate,login
from django.contrib import messages



# Create your views here.
def DeptoListView(request):
    depto_category_url_list = get_depto_cat_url_list()

    context = {
        "depto_list": depto_category_url_list,
    }
    
    return render (request,'depto_list_view.html', context)

# retorna la lista de reservas para cada usuario (y para admin muestra TODAS)
class ReservaListView(ListView):
    model = Reserva

    #aqui se hace la referencia la template, en una variable,
    #  y no en un "return render" como es el caso de una "def"
    template_name = 'reserva_list_view.html'
    
    def get_queryset(self,*args, **kwargs):
        # usuario admin podra ver TODAS las reservas
        if self.request.user.is_staff:
            reserva_list = Reserva.objects.all()
            return reserva_list

        # usuario normal solo podra ver SUS PROPIAS reservas
        else:
            reserva_list = Reserva.objects.filter(user=self.request.user)
            return reserva_list
    

class DeptoDetailView(View):
    
    # generic view based DeptoDetailView
    def get(self, request, *args, **kwargs):

        #se obtiene keyword argument desde la misma url del browser (ejemplo: desde depto iquique obtiene "IQU")
        category = self.kwargs.get('category',None)#segundo parametro = none, por si algun usuario escribe algo en la url estropearia la captura de la categoria
        
        # se obtiene categoria(ciudad) en human readable ("La Serena" en vez de 'SER')
        human_format_depto_category = get_depto_category_human_format(category)
       
        # se inicializa form vacio
        form = AvailabilityForm()

        if human_format_depto_category is not None:
            context={
            'depto_category': human_format_depto_category,
            'form': form #referencia a availability form
            }
            return render(request,'depto_detail_view.html',context)
        else:
            return HttpResponse('Departamento No Existe!')
        
  
    def post(self, request, *args, **kwargs):
        # se obtiene Depto categoria-ciudad desde kwargs
        category = self.kwargs.get('category',None)
        
        # pass request.POST into AvailibilityForm
        form= AvailabilityForm(request.POST)

        # revisa validez del form
        if form.is_valid():
            data = form.cleaned_data # form. cleaned_data is where all validated fields are stored.

        # se obtiene departamentos disponibles segun categoria y check_in + check_out ingresado x un cliente
        available_deptos = get_available_deptos(category,data['check_in'],data['check_out'])

        # checkea si hay deptos disponibles (si hay deptos disponibles en la ciudad escogida para arrendar...)
        if available_deptos is not None:
            
            if request.user.is_authenticated:
                # reserva el depto (el primero "[0]" de la categoria qe halle disponible)
                reserva = book_depto(request,available_deptos[0],
                data['check_in'],data['check_out'])
                #messages.success(request,"Reserva exitosa!")
                return redirect(to="arriendo:ReservaListView")
                #return HttpResponse(reserva)
            else:
                return HttpResponse('Por favor, inicie sesión antes de crear una reserva')
            
        else:
            #messages.error(request,"error lo sentimos")
            return HttpResponse('lo sentimos, este departamento se encuentra ocupado para tales fechas. Por favor intente con otra fecha')

       

class CancelReservaView(DeleteView):
    model = Reserva

    template_name = 'reserva_cancel_view.html'

    #al eliminar exitosamente una reserva, redirigirse lista de resrvas
    success_url = reverse_lazy('arriendo:ReservaListView')

def ubicaciones(request):
  
    ciudades = [
        ['map_vina','Viña del Mar'],
        ['map_serena','La Serena'],
        ['map_pucon','Pucon'],
        ['map_iquique','Iquique'],
        ['map_villarica','Villarica'],
        ['map_valdivia','Valdivia'],
        ['map_frutillar','Frutillar']
    ]

    data = {
        'ciudades' : ciudades
    }
    
    return render (request,'ubicaciones.html', data)
    
def registro(request):
    data = {
        'form': CustomCreationForm
    }

    if request.method=='POST':
        formulario = CustomCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            
            #para qe el usuario recien creado quede logueado altiro
            user = authenticate(username=formulario.cleaned_data["username"],password=formulario.cleaned_data["password1"])
            login(request,user)
            #messages.success(request, "te has registrado exitosamente")
            #redirigir al home
            return redirect(to="arriendo:DeptoListView")

    return render(request,'registration/registro.html',data)       

# CLASE COMENTADA A CONTINUACION PQ SE INTEGRO ESTA FUNCIONALIDAD
# EN la clase DeptoDetailView 

# class ReservaView(FormView):
#     form_class = AvailabilityForm
#     template_name = 'availability_form.html'

#     def form_valid(self, form):
#         data = form.cleaned_data
#         depto_list = Depto.objects.filter(category=data['depto_category'])
#         available_deptos=[]

#         for depto in depto_list:
#             if check_availability(depto,data['check_in'],data['check_out']):
#                 available_deptos.append(depto)
        

#         if len(available_deptos) > 0:
#             depto = available_deptos[0]
#             reserva = Reserva.objects.create(
#             user = self.request.user,
#             depto = depto,
#             check_in = data['check_in'],
#             check_out = data['check_out']
#             )
#             reserva.save()
#             return HttpResponse(reserva)
#         else:
#             return HttpResponse('lo sentimos, este departamento se encuentra ocupado para tales fechas. Por favor intente con otra fecha')


        

arriendo/templates/depto_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles Depto</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'arriendo/css/depto_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="depto">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'arriendo:DeptoListView'  %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="depto-info">
                <h1>{{depto_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="reserva-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" min="2021-07-06T00:00" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" min="2021-07-06T00:00" id="id_check_out" name="check_out">
                </div>
                

                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Reservar</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

arriendo/templates/depto_list_view.html
{% extends 'layout.html' %}
{% load static %}

{% block titulo_pagina %} Turismo Real {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'arriendo/css/depto_list_view.css' %}">
{% endblock %}

{% block contenido %}
<div class="body">
    <!-- Brand -->
    <h1 id="brand">Departamentos</h1>

    <!-- Main Content -->
    <div class="content">

        {% for depto_category, depto_url in depto_list %}
        
        <div class="depto">
            <a href="{{depto_url}}">
                <img
                    src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">

                <h2>{{depto_category}}</h2>
                <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Commodi</p>
            </a>
        </div>
        {% endfor %}

    </div>
</div>

<!--Jqery-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

arriendo/templates/layout.html
<!--este html 'layout.html'actuara como plantilla padre, osea que todos los demas
html heredaran el contenido escrito aqui, reciclando codigo-->

{% load static %}<!--se indica qe se carga la carpeta static (contenedora de css e imagnes)-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!--cada plantilla hija podra tener su propio nombre de titulo de esta manera-->
    <title>{% block titulo_pagina %} {% endblock%}</title>

    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
	
	<!--css de layout.html padre-->
    <link rel="stylesheet" href="{% static 'arriendo/css/layout.css' %}">

    <!--Css de cada html hijo-->
    {% block css %}
	{% endblock %}

</head>
<body>
    <div class="contenedor">
		
		<header>
			<div class="logo">
				<img src="{% static 'img/logo1.jpg' %}" alt="">
				<a href="#">Turismo Real</a>
			</div>

			<nav>
				<a href="{% url 'arriendo:DeptoListView' %}">Inicio</a>
				<a href="{% url 'arriendo:Ubicaciones' %}">Ubicaciones</a>
				
				{% if user.is_authenticated %}
				<a href="{% url 'arriendo:ReservaListView' %}">Mis Reservas</a>
				<a href="{% url 'logout' %}">Cerrar Sesión</a>
				<a class="nombreusuario" href="">@{{user.username}}</a>
				{% else %}
				<a href="{% url 'login' %}">Iniciar Sesión</a><!--login creado automaticante por django allauth-->
				<a href="{% url 'arriendo:registro' %}">Crear Cuenta</a><!--registro creado manualmente en view-->
				{% endif %}
				
			</nav>
		</header>

		<!--si hay mensajes desde el framewor de mensajeria de django, imprimirlos...-->
		{% if messages %}
			{% for m in messages %}
				{{m}}
			{% endfor %}
		{% endif %}

        {% block contenido %}
            <!--todo el codigo de las demas paginas hijas irá aqui-->
		{% endblock %}
       
		<footer>
			<section class="links">
				<!-- <a href="#">Fb</a> -->
				<!-- <a href="#">Insta</a> -->
			</section>

			<div class="soporte">
				<a href="#">Ayuda</a>
			</div>
		</footer>

	
	</div>

</body>
</html>

arriendo/templates/reserva_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles Depto</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'arriendo/css/depto_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1519710164239-da123dc03ef4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60">
        </div>

        <!-- Room Details -->
        <div class="depto">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'arriendo:DeptoListView'  %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="depto-info">
                <h1>{{depto_category}}</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Id optio rem saepe culpa architecto tempora
                    numquam debitis reiciendis! Quaerat laudantium consequuntur doloribus quod placeat consectetur
                    veniam,
                    rerum repellendus magnam labore. </p>
            </div>

            <!-- Div 3: Depto Cancel Reserva Form -->
            <form id="reserva-form" action="" method="POST">

                {% csrf_token %}
                <h2>¿Está Seguro que quiere cancelar esta Reserva?</h2>
                <h3>Ciudad: {{reserva.get_depto_category}}</h3>
                <h3>Fecha Entrada: {{reserva.check_in}}</h3>
                <h3>Fecha Salida: {{reserva.check_out}}</h3>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit" >Cancelar Reservar</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

arriendo/templates/reserva_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mis Reservas</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'arriendo/css/reserva_list_view.css' %}">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Sus Reservas</h1>
                <h2>Bienvenido {{user}}</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'arriendo:DeptoListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for reserva in reserva_list %}
            <div class="booking">
                <img src="https://images.unsplash.com/photo-1560067174-c5a3a8f37060?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=300&q=80"
                    alt="">
                <div class="category">
                    <h2>{{reserva.get_depto_category}}</h2>
                </div>
                <div class="from">
                    <h3>Desde: {{reserva.check_in}}</h3>
                </div>
                <div class="to">
                    <h3>Hasta: {{reserva.check_out}}</h3>
                </div>
                <div class="beds">
                    <h3>Camas: {{reserva.depto.camas}}</h3>
                </div>
                <div class="capacity">
                    <h3>Capacidad: {{reserva.depto.capacidad}}</h3>
                </div>
                <div class="cancel"><a href="{{reserva.get_cancel_reserva_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

arriendo/templates/ubicaciones.html
{% extends 'layout.html' %}
{% load static %}

{% block titulo_pagina %} Ubicaciones {% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'arriendo/css/ubicaciones.css' %}">
{% endblock %}

{% block contenido %}

<div class="container">
    
    {% for id_mapa,nombre_ciudad in ciudades %}
    <div class="ciudad">
        <div class="mapa" id="{{id_mapa}}"></div>

        <div class="detalle">
            <h2>{{nombre_ciudad}}</h2>
            <h3>Lorem, ipsum dolor.</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis, itaque!</p>

        </div>

    </div>
    {% endfor %}

    <script src="{% static 'js/maps.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD8wJ7H4mu_F51nDW0uXf903jPKumnRCDA&callback=initialize"></script>


</div>
 
{% endblock %}